language: node_js
cache:
    npm: false
node_js:
- lts/*
before_script:
- npm install -g grunt-cli npm
env:
  global:
    secure: X2PB9oS2zxBG1t66YbDIjDqt1t/CHPL53wG/SY8diAHgnq2FjoKT4bp2Y9PWsO74xw22AdaqbRowLjqJAb5cjEEINW+olyvwKGjFF6KE3smJDZtBq9twk5/mMQaOBYpbunkiuIV8yghhXUOoKUKTieJn87nLSBq27MagBTZosmwxH8ja87eLUcHfAULtf4htThznZaBBXgfqWj4kYVm/a7pA2pqnFN0YVTc4sBNjRKXjoqSxSBqTgX7fYEGKbgSxpmwbUJdPqLLtG3hFknSvsFcVJzql8R30WGeKJsh0de9Gxfm66jsKAeZ7EUiA6uimCmqFaFW1FAhrhtE0EqiI0EiNPMm7mPTiLnKDbilu5wIkf1aIKMqJ3+AcNsqG+S7CDbZbBo3yP5jxvWXZeTHfTcrHyIeTi9H7inKqQjr8ZDhahlsvkSKfIjbWf3uuXUj5+GRiaOgmzgFab1IdpMh7xolh+AfCrMbGY4ABIT8XBI8CdwLlFNHrNYE6tD9pK/0fpQD2+IQZk/KxX5TOosJj7dfKd5WCOqIN9DwJ+KXqaaegbTkxJH4DG00LDyyNqsmUGbfrzl+3ZfN+wmPFzngxlSDUqz5tPL6uHx3b8wN3bis7Fts5kGEpcPOJwCAeKFZ2+q6TJnKbhNNtWfVxgKTRJZA1xLVKcV2zP2tUPZQOunk=
